### ISSUE TITLE
[question] Is there a way to handle remote .DS_Store ?

### ISSUE THREAD

**Issue by nixawk** [al45tair/ds_store#1]
If a local [**.DS_Store**](http://search.cpan.org/~wiml/Mac-Finder-DSStore/DSStoreFormat.pod) file, [**ds_store**](https://github.com/al45tair/ds_store/) works well on it.  ex:

```
from ds_store import DSStore

def local():
    d = DSStore.open('~/.DS_Store', 'r')

    for i in d._traverse(None):
        print(i, i.filename)

if __name__ == '__main__':
    local()
```

If a remote [**.DS_Store**](http://search.cpan.org/~wiml/Mac-Finder-DSStore/DSStoreFormat.pod), ex: http://127.0.0.1/.DS_Store, how to make [**ds_store**](https://github.com/al45tair/ds_store/) work without downloading the file ?

- How to handle a normal file object with [**ds_store**](https://github.com/al45tair/ds_store/) ?

**Comment by al45tair** [comment]
`DSStore.open()` takes either a filename or a "file-like object" (which must support random access, i.e. it has to have a working `seek()` method). `urllib2.urlopen()` doesn't support random access, so you can't use that, but you *could* fetch the remote file and then either save it somewhere or use `io.BytesIO` on the data if it's in memory.

Alternatively, you could make your own random access adapter, like the example in [this StackOverflow post](https://stackoverflow.com/questions/23579088/opening-response-from-urllib2-urlopen-on-the-fly-with-zipfile-zipfile) and use that.

I'll also note that this isn't a support forum. You should probably be using [StackOverflow](https://stackoverflow.com) for this kind of question.
