### ISSUE TITLE
open issues in the old repo? 

### ISSUE THREAD

**Issue by dimpase** [al45tair/ds_store#2]
What is their status? Have they all been resolved?
Should hey be migrated here?
(my specific interest concerns https://bitbucket.org/al45tair/ds_store/issues/7)

**Comment by al45tair** [comment]
They haven't been migrated, no; unfortunately it appears Github's migration doesn't copy the issues across. As regards using `ds_store` to set background images, if you're doing it by hand then you want to be using 'pBBk' as well as 'icvp' (I've just updated that bug to explain). Alternatively you could just use `dmgbuild` which already knows what to do.
